coverage:
  status:
    project:
      default:
        # Allow total coverage to drop by at most 2%
        target: auto
        threshold: 2%
    patch:
      default:
        # Force any given PR to be at least 70% covered
        target: 70%
