name: Erlang library CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            otp_version: 24.2
            rebar_version: 3.18
            thrift_version: 0.14.2

    name: Build (${{ matrix.os }}, OTP-${{ matrix.otp_version }})
    
    runs-on: ${{ matrix.os }}

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Setup Thrift compiler
      uses: valitydev/action-setup-thrift@v0.0.4
      with:
        thrift-version: ${{ matrix.thrift_version }}

    - name: Setup BEAM
      uses: erlef/setup-beam@v1.10
      with:
        otp-version: ${{ matrix.otp_version }}
        rebar3-version: ${{ matrix.rebar_version }}

    - name: Cache Hex packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/rebar3/hex/hexpm/packages
        key: ${{ runner.os }}-otp-${{ matrix.otp_version }}-hex-${{ hashFiles('**/rebar.lock') }}
        restore-keys: |
          ${{ runner.os }}-otp-${{ matrix.otp_version }}-hex-

    - name: Cache PLTs
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/rebar3/rebar3_*_plt
          _build/default/rebar3_*_plt
        key: ${{ runner.os }}-otp-${{ matrix.otp_version }}-plt-${{ hashFiles('**/rebar.lock') }}
        restore-keys: |
          ${{ runner.os }}-otp-${{ matrix.otp_version }}-plt-

    - name: Compile
      run: make compile
    
    - name: Check formatting
      run: make check_format
    
    - name: Run xref
      run: make xref
    
    - name: Run linting
      run: make lint
    
    - name: Run dialyzer
      run: make dialyze
    
    - name: Run tests
      id: run_tests
      run: make test

    - name: Store CT Logs
      if: ${{ failure() && steps.run_tests.outcome == 'failure' }}
      uses: actions/upload-artifact@v2
      with:
        name: ct-logs
        path: _build/test/logs
