name: Erlang library CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

env:
  OTP_VERSION: 24.2
  REBAR_VERSION: 3.18
  THRIFT_VERSION: 0.14.2

jobs:
  deps:
    name: Cache dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup BEAM
        uses: erlef/setup-beam@v1.10
        with:
          otp-version: ${{ env.OTP_VERSION }}
          rebar3-version: ${{ env.REBAR_VERSION }}
      
      - name: Cache Hex packages
        id: hex_cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/rebar3/hex/hexpm/packages
          key: ${{ runner.os }}-otp-${{ env.OTP_VERSION }}-hex-${{ hashFiles('**/rebar.config') }}
          restore-keys: |
            ${{ runner.os }}-otp-${{ env.OTP_VERSION }}-hex-
      
      - name: Get dependencies
        if: steps.hex_cache.outputs.cache-hit != 'true'
        run: rebar3 deps

  build:
    name: Build / Check
    runs-on: ubuntu-latest
    needs: deps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Thrift compiler
        uses: valitydev/action-setup-thrift@v0.0.4
        with:
          thrift-version: ${{ env.THRIFT_VERSION }}
      
      - name: Setup BEAM
        uses: erlef/setup-beam@v1.10
        with:
          otp-version: ${{ env.OTP_VERSION }}
          rebar3-version: ${{ env.REBAR_VERSION }}
      
      - name: Cache Hex packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/rebar3/hex/hexpm/packages
          key: ${{ runner.os }}-otp-${{ env.OTP_VERSION }}-hex-${{ hashFiles('**/rebar.config') }}
          restore-keys: |
            ${{ runner.os }}-otp-${{ env.OTP_VERSION }}-hex-
      
      - name: Compile
        run: make compile

      - name: Check formatting
        run: make check_format
      
      - name: Run xref
        run: make xref
      
      - name: Run linting
        run: make lint

  analyze:
    name: Dialyze
    needs: deps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Thrift compiler
        uses: valitydev/action-setup-thrift@v0.0.4
        with:
          thrift-version: ${{ env.THRIFT_VERSION }}
      
      - name: Setup BEAM
        uses: erlef/setup-beam@v1.10
        with:
          otp-version: ${{ env.OTP_VERSION }}
          rebar3-version: ${{ env.REBAR_VERSION }}
      
      - name: Cache Hex packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/rebar3/hex/hexpm/packages
          key: ${{ runner.os }}-otp-${{ env.OTP_VERSION }}-hex-${{ hashFiles('**/rebar.config') }}
          restore-keys: |
            ${{ runner.os }}-otp-${{ env.OTP_VERSION }}-hex-

      - name: Cache PLTs
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/rebar3/rebar3_*_plt
            _build/test/rebar3_*_plt
          key: ${{ runner.os }}-otp-${{ env.OTP_VERSION }}-plt-${{ hashFiles('**/rebar.lock') }}
          restore-keys: |
            ${{ runner.os }}-otp-${{ env.OTP_VERSION }}-plt-      

      - name: Run dialyzer
        run: make dialyze

  test:
    name: Test
    needs: deps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Thrift compiler
        uses: valitydev/action-setup-thrift@v0.0.4
        with:
          thrift-version: ${{ env.THRIFT_VERSION }}
      
      - name: Setup BEAM
        uses: erlef/setup-beam@v1.10
        with:
          otp-version: ${{ env.OTP_VERSION }}
          rebar3-version: ${{ env.REBAR_VERSION }}
      
      - name: Cache Hex packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/rebar3/hex/hexpm/packages
          key: ${{ runner.os }}-otp-${{ env.OTP_VERSION }}-hex-${{ hashFiles('**/rebar.config') }}
          restore-keys: |
            ${{ runner.os }}-otp-${{ env.OTP_VERSION }}-hex-

      - name: Run tests
        id: run_tests
        run: make test

      - name: Store CT Logs
        if: ${{ steps.run_tests.outcome == 'failure' }}
        uses: actions/upload-artifact@v2
        with:
          name: ct-logs
          path: _build/test/logs

  cover:
    name: Cover
    needs: [build, test, analyze]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Thrift compiler
        uses: valitydev/action-setup-thrift@v0.0.4
        with:
          thrift-version: ${{ env.THRIFT_VERSION }}
      
      - name: Setup BEAM
        uses: erlef/setup-beam@v1.10
        with:
          otp-version: ${{ env.OTP_VERSION }}
          rebar3-version: ${{ env.REBAR_VERSION }}
      
      - name: Cache Hex packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/rebar3/hex/hexpm/packages
          key: ${{ runner.os }}-otp-${{ env.OTP_VERSION }}-hex-${{ hashFiles('**/rebar.config') }}
          restore-keys: |
            ${{ runner.os }}-otp-${{ env.OTP_VERSION }}-hex-
