name: Erlang library CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

env:
  OTP_VERSION: 24.2
  REBAR_VERSION: 3.18
  THRIFT_VERSION: 0.14.2

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup BEAM
        uses: erlef/setup-beam@v1.10
        with:
          otp-version: ${{ env.OTP_VERSION }}
          rebar3-version: ${{ env.REBAR_VERSION }}
      
      - &cache_build
        name: Cache _build
        uses: actions/cache@v2
        with:
          path: _build/default/lib
          key: ${{ runner.os }}-otp-${{ env.OTP_VERSION }}-build-${{ hashFiles('**/rebar.lock') }}
          restore-keys: |
            ${{ runner.os }}-otp-${{ env.OTP_VERSION }}-build-

      - name: Compile
        run: make compile

  check:
    name: Check
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Thrift compiler
        uses: valitydev/action-setup-thrift@v0.0.4
        with:
          thrift-version: ${{ env.THRIFT_VERSION }}
      
      - name: Setup BEAM
        uses: erlef/setup-beam@v1.10
        with:
          otp-version: ${{ env.OTP_VERSION }}
          rebar3-version: ${{ env.REBAR_VERSION }}
      
      - *cache_build
      
      - name: Check formatting
        run: make check_format
      
      - name: Run linting
        run: make lint

      - name: Run xref
        run: make xref

  analyze:
    name: Dialyze
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Thrift compiler
        uses: valitydev/action-setup-thrift@v0.0.4
        with:
          thrift-version: ${{ env.THRIFT_VERSION }}
      
      - name: Setup BEAM
        uses: erlef/setup-beam@v1.10
        with:
          otp-version: ${{ env.OTP_VERSION }}
          rebar3-version: ${{ env.REBAR_VERSION }}

      - *cache_build

      - name: Cache PLTs
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/rebar3/rebar3_*_plt
            _build/test/rebar3_*_plt
          key: ${{ runner.os }}-otp-${{ env.OTP_VERSION }}-plt-${{ hashFiles('**/rebar.lock') }}
          restore-keys: |
            ${{ runner.os }}-otp-${{ env.OTP_VERSION }}-plt-      

      - name: Run dialyzer
        run: make dialyze

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Thrift compiler
        uses: valitydev/action-setup-thrift@v0.0.4
        with:
          thrift-version: ${{ env.THRIFT_VERSION }}
      
      - name: Setup BEAM
        uses: erlef/setup-beam@v1.10
        with:
          otp-version: ${{ env.OTP_VERSION }}
          rebar3-version: ${{ env.REBAR_VERSION }}

      - *cache_build

      - name: Run tests
        id: run_tests
        run: make test

      - name: Store CT Logs
        if: ${{ steps.run_tests.outcome == 'failure' }}
        uses: actions/upload-artifact@v2
        with:
          name: ct-logs
          path: _build/test/logs

      - name: Run cover analysis
        run: make cover

      - name: Upload cover stats
        uses: codecov/codecov-action@v2
        with:
          files: _build/test/covertool/*.covertool.xml
